<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TraineeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $trainees = [
            // Active Trainees
            [
                'Trainee_Name' => 'John Doe',
                'Trainee_Phone' => '0771234567',
                'Trainee_NIC' => '200112345678',
                'Trainee_Email' => 'john.doe@email.com',
                'Training_StartDate' => '2024-11-20',
                'Training_EndDate' => '2025-10-20',
                'Institute' => 'University of Moratuwa',
                'Languages_known' => 'Java, Python, JavaScript',
                'Supervisor' => 'Mr. Smith',
                'Target_Date' => '2025-06-15',
                'Trainee_HomeAddress' => 'Colombo',
                'AssignedWork_Description' => 'Backend Development - REST API implementation',
                'field_of_specialization' => 'Software Engineering',
                'payment_start_date' => null,
                'payment_end_date' => null,
                'requested_payment_date' => null,
                'absent_Count' => 0,
                'terminated_date' => null,
                'terminated_reason' => null,
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'Trainee_Name' => 'Jane Smith',
                'Trainee_Phone' => '0779876543',
                'Trainee_NIC' => '200298765432',
                'Trainee_Email' => 'jane.smith@email.com',
                'Training_StartDate' => '2024-11-28',
                'Training_EndDate' => '2025-10-28',
                'Institute' => 'SLIIT',
                'Languages_known' => 'Python, R, SQL',
                'Supervisor' => 'Dr. Johnson',
                'Target_Date' => '2025-07-01',
                'Trainee_HomeAddress' => 'Kandy',
                'AssignedWork_Description' => 'Data Analysis and Machine Learning Models',
                'field_of_specialization' => 'Data Science',
                'payment_start_date' => null,
                'payment_end_date' => null,
                'requested_payment_date' => null,
                'absent_Count' => 1,
                'terminated_date' => null,
                'terminated_reason' => null,
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'Trainee_Name' => 'Michael Brown',
                'Trainee_Phone' => '0762345678',
                'Trainee_NIC' => '200334567890',
                'Trainee_Email' => 'michael.b@email.com',
                'Training_StartDate' => '2025-01-15',
                'Training_EndDate' => '2025-12-15',
                'Institute' => 'IIT',
                'Languages_known' => 'JavaScript, TypeScript, React',
                'Supervisor' => 'Ms. Williams',
                'Target_Date' => '2025-08-20',
                'Trainee_HomeAddress' => 'Galle',
                'AssignedWork_Description' => 'Frontend Development - React Components',
                'field_of_specialization' => 'Web Development',
                'payment_start_date' => null,
                'payment_end_date' => null,
                'requested_payment_date' => null,
                'absent_Count' => 0,
                'terminated_date' => null,
                'terminated_reason' => null,
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'Trainee_Name' => 'Sarah Johnson',
                'Trainee_Phone' => '0752468135',
                'Trainee_NIC' => '200445678901',
                'Trainee_Email' => 'sarah.j@email.com',
                'Training_StartDate' => '2024-12-01',
                'Training_EndDate' => '2025-11-30',
                'Institute' => 'NSBM',
                'Languages_known' => 'Kotlin, Java, Swift',
                'Supervisor' => 'Mr. Davis',
                'Target_Date' => '2025-07-15',
                'Trainee_HomeAddress' => 'Negombo',
                'AssignedWork_Description' => 'Mobile App Development - Android & iOS',
                'field_of_specialization' => 'Mobile App Development',
                'payment_start_date' => null,
                'payment_end_date' => null,
                'requested_payment_date' => null,
                'absent_Count' => 2,
                'terminated_date' => null,
                'terminated_reason' => null,
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'Trainee_Name' => 'David Wilson',
                'Trainee_Phone' => '0763691472',
                'Trainee_NIC' => '200556789012',
                'Trainee_Email' => 'david.w@email.com',
                'Training_StartDate' => '2025-02-01',
                'Training_EndDate' => '2026-01-31',
                'Institute' => 'Uva Wellassa University',
                'Languages_known' => 'Python, C++, Assembly',
                'Supervisor' => 'Dr. Martinez',
                'Target_Date' => '2025-09-01',
                'Trainee_HomeAddress' => 'Matara',
                'AssignedWork_Description' => 'Network Security and Penetration Testing',
                'field_of_specialization' => 'Cybersecurity',
                'payment_start_date' => null,
                'payment_end_date' => null,
                'requested_payment_date' => null,
                'absent_Count' => 0,
                'terminated_date' => null,
                'terminated_reason' => null,
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Inactive Trainees
            [
                'Trainee_Name' => 'Emily Davis',
                'Trainee_Phone' => '0774567890',
                'Trainee_NIC' => '200167890123',
                'Trainee_Email' => 'emily.d@email.com',
                'Training_StartDate' => '2024-08-01',
                'Training_EndDate' => '2025-07-31',
                'Institute' => 'University of Colombo',
                'Languages_known' => 'Java, Spring Boot',
                'Supervisor' => 'Mr. Anderson',
                'Target_Date' => '2025-04-01',
                'Trainee_HomeAddress' => 'Dehiwala',
                'AssignedWork_Description' => 'Enterprise Application Development',
                'field_of_specialization' => 'Software Engineering',
                'payment_start_date' => null,
                'payment_end_date' => null,
                'requested_payment_date' => null,
                'absent_Count' => 5,
                'terminated_date' => '2024-12-15',
                'terminated_reason' => 'Personal reasons - family emergency',
                'status' => 'inactive',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'Trainee_Name' => 'Robert Taylor',
                'Trainee_Phone' => '0765432109',
                'Trainee_NIC' => '200278901234',
                'Trainee_Email' => 'robert.t@email.com',
                'Training_StartDate' => '2024-09-15',
                'Training_EndDate' => '2025-08-15',
                'Institute' => 'NIBM',
                'Languages_known' => 'PHP, Laravel, MySQL',
                'Supervisor' => 'Ms. Thompson',
                'Target_Date' => '2025-05-01',
                'Trainee_HomeAddress' => 'Kurunegala',
                'AssignedWork_Description' => 'Web Application Development',
                'field_of_specialization' => 'Web Development',
                'payment_start_date' => null,
                'payment_end_date' => null,
                'requested_payment_date' => null,
                'absent_Count' => 8,
                'terminated_date' => '2025-01-10',
                'terminated_reason' => 'Health issues requiring extended leave',
                'status' => 'inactive',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'Trainee_Name' => 'Lisa Anderson',
                'Trainee_Phone' => '0758901234',
                'Trainee_NIC' => '200389012345',
                'Trainee_Email' => 'lisa.a@email.com',
                'Training_StartDate' => '2024-10-01',
                'Training_EndDate' => '2025-09-30',
                'Institute' => 'Wayamba University',
                'Languages_known' => 'Python, TensorFlow, Keras',
                'Supervisor' => 'Dr. White',
                'Target_Date' => '2025-06-01',
                'Trainee_HomeAddress' => 'Anuradhapura',
                'AssignedWork_Description' => 'AI Model Development',
                'field_of_specialization' => 'Artificial Intelligence',
                'payment_start_date' => null,
                'payment_end_date' => null,
                'requested_payment_date' => null,
                'absent_Count' => 3,
                'terminated_date' => '2024-12-20',
                'terminated_reason' => 'Accepted full-time job offer',
                'status' => 'inactive',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Paid Trainees
            [
                'Trainee_Name' => 'James Wilson',
                'Trainee_Phone' => '0779012345',
                'Trainee_NIC' => '199990123456',
                'Trainee_Email' => 'james.w@email.com',
                'Training_StartDate' => '2023-11-01',
                'Training_EndDate' => '2024-10-31',
                'Institute' => 'University of Peradeniya',
                'Languages_known' => 'Java, Python, C++',
                'Supervisor' => 'Dr. Brown',
                'Target_Date' => '2024-06-30',
                'Trainee_HomeAddress' => 'Kandy',
                'AssignedWork_Description' => 'Full Stack Development',
                'field_of_specialization' => 'Software Engineering',
                'payment_start_date' => '2024-11-01',
                'payment_end_date' => '2024-12-31',
                'requested_payment_date' => '2024-10-25',
                'absent_Count' => 1,
                'terminated_date' => null,
                'terminated_reason' => null,
                'status' => 'paid',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'Trainee_Name' => 'Maria Garcia',
                'Trainee_Phone' => '0761234567',
                'Trainee_NIC' => '200001234567',
                'Trainee_Email' => 'maria.g@email.com',
                'Training_StartDate' => '2024-01-15',
                'Training_EndDate' => '2024-12-15',
                'Institute' => 'SLIIT',
                'Languages_known' => 'JavaScript, Node.js, React',
                'Supervisor' => 'Mr. Lee',
                'Target_Date' => '2024-08-01',
                'Trainee_HomeAddress' => 'Colombo',
                'AssignedWork_Description' => 'MERN Stack Development',
                'field_of_specialization' => 'Web Development',
                'payment_start_date' => '2024-12-16',
                'payment_end_date' => '2025-01-15',
                'requested_payment_date' => '2024-12-10',
                'absent_Count' => 0,
                'terminated_date' => null,
                'terminated_reason' => null,
                'status' => 'paid',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'Trainee_Name' => 'Kevin Martinez',
                'Trainee_Phone' => '0772345678',
                'Trainee_NIC' => '200112345679',
                'Trainee_Email' => 'kevin.m@email.com',
                'Training_StartDate' => '2024-03-01',
                'Training_EndDate' => '2025-02-28',
                'Institute' => 'IIT',
                'Languages_known' => 'Swift, Objective-C, Flutter',
                'Supervisor' => 'Ms. Chen',
                'Target_Date' => '2024-10-15',
                'Trainee_HomeAddress' => 'Gampaha',
                'AssignedWork_Description' => 'iOS and Cross-platform Development',
                'field_of_specialization' => 'Mobile App Development',
                'payment_start_date' => '2025-03-01',
                'payment_end_date' => '2025-04-30',
                'requested_payment_date' => '2025-02-20',
                'absent_Count' => 2,
                'terminated_date' => null,
                'terminated_reason' => null,
                'status' => 'paid',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('trainees')->insert($trainees);
    }
}
